### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#11]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/7252105/66076458-201d7a00-e55e-11e9-8c2d-b533d937514f.png">

After filling in all the details for IPCI i could not save it unfortunately.

**Comment by alina-trifan** [comment]
IPCI database was saved on the catalogue, however we suspect there is a bug somewhere in the last section of the questionnaire and only that section was not saved properly. We will look into it.

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
The problem was an update in the Pubmed API that changed a little bit the requests' format, and this questionnaire's component uses this API. All the work you have done was saved except in the last question set, which contains this component.

**Comment by joaorafaelalmeida** [comment]
This issue is solved in the test version and will be in the next EHDEN Portal release.
