### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#14]
- [x] Note that the title is missing the word Network.

- [x] Would change this text now to:

The EHDEN consortium will implement a federated health data network in Europe, enhance the supply and demand side to form a health data eco-system in compliance with robust privacy and ethics governance, and enable the development of new and augmented health services through available and expanded technologies, in the interest of improving health outcomes.

**To:**
The European Health Data & Evidence Network (EHDEN) project aspires to be the trusted observational research ecosystem to enable better health decisions, outcomes and care. Its mission is to provide a new paradigm for the discovery and analysis of health data in Europe, by building a large-scale, federated network of data sources standardized to the OMOP common data model.

- [x] Lower on the page it says:

"The EHDEN Portal has several applications available to support the research in healthcare studies."

suggest to change to:

"The EHDEN Portal provides access to several applications that enable observational research"

- [x] You need to add the IMI Disclaimer:

"EHDEN
The European Health Data & Evidence Network has received funding from the Innovative Medicines Initiative 2 Joint Undertaking (JU) under grant agreement No 806968. The JU receives support from the European Union’s Horizon 2020 research and innovation programme and EFPIA."

- [x] Are the components customizable, e..g not show the map/references. I would not show them, The references are also not from EHDEN.

- [ ] Should we add this is underdevelopment?

- [x] At the bottom it says:

"Central to EHDEN will be the standardisation of health data to the OMOP common data model and the adoption of analytical tools developed by the international Observational Health Data Sciences and Informatics (OHDSI) open science collaboration."

and then a button to learn more. Maybe we can add the learn more to the text at the top of the page?.   Would also change "will" to "is" not the project is running

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
I saw the issues you reported in this post, and I solved almost all the points. However, I have two comments/questions:
1. What do you mean with "Should we add this is underdevelopment?"
2. I removed the map and references from this landing page. The references are automatically searched PubMed, but the API finds these three articles with the keyword "EHDEN". I think this is a problem related to query refinements. I will solve that.

**Comment by PRijnbeek** [comment]
Thanks for the quick changes!

1. I mean do we need to make a statement that this tool is still under development and is not accessible yet? It looks like anyone can make an account now but we have no formal procedure yet for this correct?

2. Yes I suggest to remove them on the landing page indeed until we decide differently at a later point

**Comment by joaorafaelalmeida** [comment]
In the landing page, after "Applications available", we added the following sentence: It is still under development and some features are not final.
