### ISSUE TITLE
Login with Elixer

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#15]
I am getting this message:

![image](https://user-images.githubusercontent.com/7252105/74170986-0ee02a80-4c2e-11ea-8d94-69499cdf9769.png)

How to fix this and why does this happen?

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
This was a redirect problem related to the Elixir component that we integrated into the Portal. Yesterday I changed some configs in the installation to have all the system working under the "portal.ehden.eu" domain without the old redirect to "bioinformatics.ua.pt/ehden", and the Elixir component didn't handle very well with this change, but it is now solved. I am sorry for the inconvenience and thank you for detecting it.
