### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#17]
- [ ] We need have a session to brainstorm about the homepage layout. It would probably be nice to see some more text to guide the user etc. 
- [ ] The map is zoomable but hard to control with the mouse and when i move over the page it changes. 
- [ ] Recent publications is from the data partners i assume (if so make this Recent Publications Data  Partners)? or are these publications we search for on the net with a tag? It would be nice if this is scrollable so you could see all of them instead of the top 5 (maybe this is already the case). It would be very nice if this would list all the publication that have the word OHDSI or EHDEN in their abstract?

**Comment by aspedrosa** [comment]
Since this issue is old and since now we moved away from some of these ideas I will close this issue.
