### ISSUE TITLE
Plugins not in new tab

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#18]
I think we need to investigate how to avoid the new tab opening for the plugins. It would be much nicer if this does not happen because now the portal is a bit like favourite websites bar and you do not get the feeling it is one eco-system.

we control all the sites we embed so we should be able to get around this same origin x-frame-options header issue.

For example for the Academy we can do this in the backend and switch it off:
I had same issue when I tried embed moodle 2 in iframe, solution is Site administration ► Security ► HTTP security and check Allow frame embedding

This would allow you to see the Academy in the portal.

The same should be possible for the other sites. For example for the Superset:
https://stackoverflow.com/questions/54219101/apache-superset-dashboard-in-webpage

See also for example for some information:
https://stackoverflow.com/questions/6666423/overcoming-display-forbidden-by-x-frame-options

@alina-trifan can we try this for example for the academy?

**Comment by alina-trifan** [comment]
Thanks Peter, I'll ping @joaorafaelalmeida as he is the one that has been looking into this issue

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
I tested with the Academy and it was not possible to iframe it (as we discuss in the morning). Error:

> Load denied by X-Frame-Options: “sameorigin” from “https://academy.ehden.eu/”, site does not permit cross-origin framing from “https://portal.ehden.eu/"

This is normal to happen, but I thought that using the same domain ''ehden.eu'', we didn't need to configure anything in the servers. The solution is what you pointed in the examples. If you need any help, please let me know.

**Comment by PRijnbeek** [comment]
Academa should as off today be working in iframe. tested by us. We added the portal and test server in the list of websites to allow this, please test.

Atlas is also already possible.

Arachne and Athena we need to look into.

**Comment by joaorafaelalmeida** [comment]
The only plugin that we were not able to integrate without calling it in a new Tab was the Arachne and the EHDEN Forum. However, those do not depend on us. I think we can close this issue and open a new in the repository dedicated to the Arachne and EHDEN Forum.
