### ISSUE TITLE
Allow icons for the custom components

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#2]
Would be nice if we can allow custom icons for the custom components, e.g. 

![image](https://user-images.githubusercontent.com/7252105/56723910-3111c600-674a-11e9-915b-cd52510c0d49.png)

but then of course from the same icon set to match the style

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
The latest version of the portal has already this feature. Currently, we set some icons that we found interesting (see in the pictures both menus), but we can change for others if you want.

![long menu](https://user-images.githubusercontent.com/17878072/60662641-d638d100-9e54-11e9-933c-e813ecacc9d7.png)
![short menu](https://user-images.githubusercontent.com/17878072/60662648-da64ee80-9e54-11e9-8972-261319103151.png)

**Comment by lhjohn** [comment]
Just for reference, [this](https://iconify.design/icon-sets/fa/graduation-cap.html) is the vector file of the graduation cap we used for the EHDEN Academy.

**Comment by joaorafaelalmeida** [comment]
@lhjohn Thank you for the suggestion.
