### ISSUE TITLE
CDM-BI Uploader

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#20]
1) I think we should not call this CDM-BI it is not about Business Intelligence. Change the tab name to Dashboard and the text next to the icon to "Dashboard Data Upload"

2) Suggested text updates on the page:

Export Achilles Results
The Achilles tool generates summary statistics of the database that can be visualised in the Network Dashboard in the EHDEN portal. Information about the tool can be found on the OHDSI Github Page. (add link: https://github.com/OHDSI/Achilles). One the Achilles tool has run against your database you need to export the achilles results table to a csv file.

Upload Achilles Results
The next step is to upload the Achilles result file in the portal using the form below. To update an existing database, you can simply upload the file and the data will be replaced. This operation can take some time to finish.

Auto update dashboard
Once the Achilles results have been uploaded, all the graphs in the Network Dashboard will show the most recent data.

Note: Currently there is no export to csv function in Achilles R I will ask for this that would make it easier.

3) Slug -> Acronym

4) Link to the Homepage is external i assume? can we not take this from the fingerprint? or is this the link to the Finger print? if so, we can auto fill this i think

5) I assume this Tab is only visible if you are the owner of the tool correct?

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
The points 1, 2 and 3 were addressed as you requested, as well as the suggestion gave [here](https://github.com/EHDEN/Portal/issues/40) regarding the text in the Achilles upload tab.
Answering point 4: This link is the same as asked in the question 1.05  of the fingerprint.
Answering point 5: Yes.
