### ISSUE TITLE
New views databases

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#21]
Like these new views, a few questions:

- How to add the image of the database?
- Not really clear what the information is in the row image view suggest to add a header.
- Card view, nice, can you specify what information is shown in some way? We need to agree what is on it based on the users.

**Comment by joaorafaelalmeida** [comment]
We can schedule a TC to discuss this issue if you prefer, but I will try to explain how this works.
The fields in the new views are customizable as following:
1) Table view: It is possible to select the fields to display, which will also be associated with the fields in the filters.
2) List View: This one is divided into two sections (Figure below). The fields in section 0 can have the label or just the answer in the database to that field. The fields in section 1 can have an icon, a label, both, or just the answer.
![view-list](https://user-images.githubusercontent.com/17878072/81102932-3b8f9f80-8f08-11ea-8e52-c8c7b971ca52.png)

3) Card View: This is divided into three sections (Figure below). Section 1 and 2 can have an icon, a label, both, or just the answer in the database to that field. Section 0 can have an icon or just the answer.
![view-card](https://user-images.githubusercontent.com/17878072/81102937-3e8a9000-8f08-11ea-8778-b75877c1ec31.png)

Regarding the logo, this is a type of question in the questionnaire that it is not currently present in the EHDEN questionnaire. But I will add it in the first question set if you agree. The current selection is an example, but we can define what you think is more suitable in each view.

**Comment by joaorafaelalmeida** [comment]
This issue was already discussed in some TCs and it is currently solved.
