### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#22]
Like this new option!

The order of the items is a bit strange.

I think Filter by Name, Department Name, Institute, Database Acronym is more a search function since it will almost always return one row. Can we change what we filter on now in some way?

**Comment by joaorafaelalmeida** [comment]
The fields in the filter are related to the fields selected in for each view (discussion open at #21 ). However, depending on the field's type, the filter will be different. For instance, a String entry will behave as a searching filter (Figure below marked in green), but the numeric and date fields will allow filters based on a range of values (Figure below marked in red).


![filters](https://user-images.githubusercontent.com/17878072/81105053-4b5cb300-8f0b-11ea-86bc-8e01d7994d63.png)
