### ISSUE TITLE
Custom View Catalogue

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#24]
I am not able to select something

![image](https://user-images.githubusercontent.com/7252105/81063699-a2956000-8ed8-11ea-8d36-c3e76088ba9f.png)

**Comment by joaorafaelalmeida** [comment]
This issue is similar to #19. The permissions to access the databases' information were disabled. Now you should be able to see the 3 databases (you only can see the non-draft databases in this view).
