### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#25]
i see an error under subscribed databases

![image](https://user-images.githubusercontent.com/7252105/81063919-fef87f80-8ed8-11ea-97a9-65bc38aa39a6.png)

It is unclear to me what the Tag Cloud is about? is this tagged from the answers? if not you will always see the questions as is the case now.

**Comment by joaorafaelalmeida** [comment]
This dashboard is currently deactivated to avoid confusion with the network dashboard. However, we will solve this issue and rethink how this view can be useful for the users in the Catalogue.
