### ISSUE TITLE
The Help pages still reflect the older functionality

### ISSUE THREAD

**Issue by alina-trifan** [EHDEN/Portal#29]

**Comment by PRijnbeek** [comment]
As suggested to @joaorafaelalmeida i think it is best to replace the Help page with a wiki page that can be edited outside of the portal. For example, we could use a a github.io page like we use in OHDSI: https://ohdsi.github.io/Hades/ 

In that way we can update these things without the need for a portal update. Alternative is to add a wordpress installation on the server we can add as a component so we can do whatever we want there and create informative pages etc in the portal.

**Comment by joaorafaelalmeida** [comment]
We updated the documentation in the EHDEN Portal, but with the WordPress integration, this will be again updated. However, I think this issue is already solved with the current update.
