### ISSUE TITLE
Side bar animation

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#34]
Would it not be an idea to use this type of effect?

https://code.tutsplus.com/tutorials/making-a-sliding-side-navigation-menu-for-responsive-designs--cms-28400

https://tympanus.net/Development/SidebarTransitions/

https://ourcodeworld.com/articles/read/325/top-10-best-slide-sidebar-menu-drawer-javascript-and-jquery-plugins

many other options.

**Comment by joaorafaelalmeida** [comment]
The current version of the left menu bar was already updated. However, for now, we will keep it that way, but in the future, we can return to these suggestions.
