### ISSUE TITLE
Sign up and login problems

### ISSUE THREAD

**Issue by lhjohn** [EHDEN/Portal#36]
Hi,

I just tried to log into the portal using Elixir and it gave the following empty site:
<img width="917" alt="Screenshot 2020-05-19 at 12 00 29" src="https://user-images.githubusercontent.com/7384198/82316403-06d21c80-99cd-11ea-8866-9375c69ea1be.png">

Then, I tried creating a new account. I think the reCAPTCHA might be broken on the sign up form:
<img width="617" alt="Screenshot 2020-05-19 at 12 00 08" src="https://user-images.githubusercontent.com/7384198/82316469-223d2780-99cd-11ea-9e76-98c0b4515411.png">

I also was not able to create the new account (error 500):
<img width="1102" alt="Screenshot 2020-05-19 at 11 59 53" src="https://user-images.githubusercontent.com/7384198/82316512-308b4380-99cd-11ea-924d-5433cd86427b.png">

**Comment by PRijnbeek** [comment]
@alina-trifan this still an issue can this be give some attention @alina-trifan?

**Comment by alina-trifan** [comment]
Hi both, 

Regular registration has been fixed, so users can register by creating an EHDEN account. We are still looking into the ELIXIR issue, there have been some changes in the communication with ELIXIR and they require more of our attention.

**Comment by PRijnbeek** [comment]
Any updates on this @alina-trifan?

**Comment by alina-trifan** [comment]
Hi @PRijnbeek, users can register by creating an account on the EHDEN portal. The ELIXIR issue is not fixed yet and probably the better solution for now would be to hide the functionality until it gets solved. We will have to discuss this internally, as we no longer have an "ELIXIR specialist" and the learning curve might slow down the process.

**Comment by joaorafaelalmeida** [comment]
This issue is currently solved.
