### ISSUE TITLE
Make sidebar main buttons navigate to tool page

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/Portal#37]
In the sidebar, when I click 'Catalogue' nothing happens. I have to click on one of the subitems. Ideally clicking on catalogue would get me to the overview page of the catalogue page (same as what happens when clicking on 'Databases' submenu).
![image](https://user-images.githubusercontent.com/17825660/85292690-95d6c680-b49c-11ea-85ea-c6749da0f1e6.png)

Same for 'Dashboard'.

**Comment by aspedrosa** [comment]
Since now we have a HOME button I feel that this is no longer an issue.
