### ISSUE TITLE
Dashboard Data upload

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#40]
A few points:

1. If have worked on a new R-package to extract the information we need for the dashboard: [https://github.com/EHDEN/CatalogueExport](https://github.com/EHDEN/CatalogueExport). This is strongly based on the great Achilles code but we can add our own analysis now very easily. It will create new catalogue_results table so the user can see and store in the database what data we are exporting.

2. I like to remove the fields in the upload form and add these in the output as a specific analysisID (above 5000 to never class with Achilles analysisIds). After the upload you can simply get the strata from this analysisId to automatically fill in these fields. @joaorafaelalmeida can we have a chat about this. I now added analysisID=5000 with 

AnalysisID | stratum_1 | stratum_2 | stratum_3 | stratum_4 | stratum_5 | count
-- | -- | -- | -- | -- | -- | --
0 | Integrated Primary Care Information | 0.0.1 | Jul 19 2020  8:02PM | NA | NA | 1000
5000 | Integrated Primary Care Information | 2020-07-01 | 2020-07-07 | 5.3.1 | NA | 9999

analysisId=0 already has the R-package version and the execution date and time. analysisId=5000 had the Source_release_date, CDM_release_date, CDM version

3. I would remove the CDM-BI uploader text and change this to Dashboard Data Upload.

4. Change the text to: "Upload new database characteristics" add a line "for more information see the CatalogueExport R-package" and make this a link.

5. Remove the has header option and do not allow any without. Give an error message with a link to the package in case it is not in the right format.

**Comment by PRijnbeek** [comment]
Currently the Dashboard Data Upload page is blank in the production version!

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
Regarding the first comment:
2. Totally agree, it is a great idea. Since the information is present in the Achilles, it will be better to extract it from there. We are working on that.
3. We did that change in the Portal, but I noticed now that inside of the component, the text is still there. We will change it.
4. We already changed this, but will only be able in next deployment (this week)
5. Same here.

Regarding your last comment, @aspedrosa have been doing a few updates (superset version, etc.) and the configuration changed a bit regarding the feature of embedding the system in external tools. However, it is already solved, you can try it again.

**Comment by aspedrosa** [comment]
Currently we are asking these four fields on the uploader form:
1. Achilles version
2. Achilles generation date
3. CDM version
4. Vocabulary version

If I understand correctly, I can get 1 and 2 with stratums 1 and 2 from the analysis_id=0 respectively. 3 is the stratum 4 of analysis_id=5000. But 4 is missing.

With this I don't understand the utility stratums 2 and 3 of analysis_id=5000

**Comment by joaorafaelalmeida** [comment]
@aspedrosa I think the stratum 2 and 3 of the analysis_id=5000 are not in the initial form, but it is new extra information about the database. What is missing, in my opinion, is the **Vocabulary version**. 
@PRijnbeek should we keep the vocabulary version? If yes, is it possible to add it, for instance, in the stratum_5 of analysis_id=5000?

**Comment by PRijnbeek** [comment]
Yes  we can add it in stratum_5 of analysis_id=5000. I will add it, for now to move just add it manually in the output file from IPCI if you like to test.

**Comment by PRijnbeek** [comment]
Actually it is already [there](https://github.com/EHDEN/CatalogueExport/blob/a13b88941b4855db157ddd9d23187e141ed982fd/inst/sql/sql_server/analyses/5000.sql#L4) but is was not filled in in the cdm_source table which is why it was empty. We could also get it from the vocabulary table maybe

**Comment by PRijnbeek** [comment]
Thanks for the update. A few minor things:

![image](https://user-images.githubusercontent.com/7252105/94491819-3ef23300-01e9-11eb-8a6f-2f3ee4a1db42.png)

1. When i go to the page a spinning wheel is shown on the top saying it is uploading?
2. Remove all references to Achilles in the text, e..g  Achilles Version -> R Package Version, Achilles Generation Data -> Generation Date. etc.

If i click on Edit i see this:

<img width="1514" alt="image" src="https://user-images.githubusercontent.com/7252105/94492012-9b555280-01e9-11eb-9ce5-70d018631a1d.png">

1. Suggest to remove all the text on the top since that is not on this page and incorrect (not Achilles).
2.The release date can be removed since that is also in the uploaded file.
3. Database Type -> is it possible to show the types already in the database or make this a pulldown with fixed types? risk is now that one says GP other gp or is this taken care of?

I have not tested a new upload yet.

Thanks for the great work so far.

**Comment by aspedrosa** [comment]
1. Spinning wheel: I tested on Brave and Firefox and I don't see it. Which browser are you using?
2. Remove all references to Achilles: What about achilles results file? results file?

Edit:
1. --
   2. Currently we are requesting the `release date` field on the creation form of a datasource and is mandatory. Should we keep it like this or make it not mandatory?
2. We are already filling the autocomplete with all options from the database. I think on previous versions we were simply storing the value, hence the two `GP` repeated values. Now we use the [title](https://docs.python.org/3.8/library/stdtypes.html#str.title) python method on the user input.

**Comment by PRijnbeek** [comment]
Please run the R package securely within your local environment without disclosing any patient identifiable information to access the Achilles result files. 

change to ->
Please run the R package (https://github.com/CatalogueExport) against your CDM to generate the results file.

**Comment by joaorafaelalmeida** [comment]
We addressed all the discussed suggestion on this issue. Please confirm if it is everything as we requested, and if you want to change anything, please let us know.

**Comment by PRijnbeek** [comment]
Let me test it tomorrow with a new extraction.

**Comment by PRijnbeek** [comment]
What is the reason i see this for IPCI:

![image](https://user-images.githubusercontent.com/7252105/95252015-b133ca80-081c-11eb-9f7a-6ad6f5267d94.png)

And this for SIDIAP:

![image](https://user-images.githubusercontent.com/7252105/95252093-cc9ed580-081c-11eb-9054-0e29fec7f13d.png)

**Comment by joaorafaelalmeida** [comment]
The IPCI view bypasses the initial form because it was already filled and you only need to upload the Achilles export file.
In the SIDIAP database, this form was not filled yet, so the system asks it first.
