### ISSUE TITLE
Certificate is expired

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#41]
<img width="747" alt="image" src="https://user-images.githubusercontent.com/7252105/90228688-f20ff400-de16-11ea-8263-d96b762cc493.png">

Suggest to setup the automatic method to get a new certificate!

**Comment by joaorafaelalmeida** [comment]
Hi Peter, I forgot to mention that this issue is already solved, the university sysadmins already updated the certificate.
In September, we will discuss internally a strategy to update this certificate automatically or to use one certificate with greater validity.
