### ISSUE TITLE
Detailed view Fingerprint Suggestions

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#43]
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/7252105/94338311-7dbd9880-fff1-11ea-911f-0bb331f2352e.png">

A few suggestion to improve this view:

1. it is unclear to the user why there is a checkbox. I suggest to remove this. Maybe it has a function for the DB owner but even then it should not be shown to other users. Am i seeing these because I am owner?
2. The comment option i like but the icon should only be shown if there is a comment added by the data owner. Is that the case?
3. Would remove all the numbers before the items. 1.04.03 City -> City. Same in the summary view, remove the Nr. Columns

**Comment by joaorafaelalmeida** [comment]
This was already discussed in a previous TC. For now, we removed the checkbox and the comment balloon. However, we will update the comment feature and bring it back in the future, if we think it is a useful feature.
Regarding the topic 3, we removed the numbers but we can bring them back any time from the admin console, if necessary.
