### ISSUE TITLE
New Database Level Dashboard

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#44]
Hi @joaorafaelalmeida,

I have created an updated version of the database level dashboard (Tabbed Database Dashboard) that contains for now all the information needed i think. Some updates still needed but this is a good start.

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/7252105/94365852-77ecb380-00d4-11eb-827e-fde45041323a.png">

A few remarks:

The Data Source Filter on the top needs to be hidden as was done in css in the other one (sorry had to remove that to play with that dashboard). It then has to set to the name of the database you are in. It was not clear how this was programmatically done, i filter on the full name now. Can you try this.

On the Concept Browser tab we need to do a trick since the filter needs to be added in the tab not above i think otherwise the search will still be across all data sources. Maybe there is another way to solve this?

For the network dashboard we can use the same approach instead of having all the tabs in the portal you make two:

1) General (that has a dashboard with the network growth, map etc)
2) Detailed (that refers to a tabbed version (We can use the same of another version, i like the name columns, and legends to be removed when you are on the database level since that is already clear in that version (not sure if this can be overruled when you are on database level in the dashboard CSS or we need to make two versions of each graph ...)

**Comment by joaorafaelalmeida** [comment]
This was already discussed in a TC.
The Database Level Dashboard is already integrated into the EHDEN Portal.
The Network dashboards are still in progress, but soon will be also available in production.

**Comment by joaorafaelalmeida** [comment]
This is already done (also mentioned in #55)
