### ISSUE TITLE
Account Creation Form Additional Questions.

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#48]
Is it possible to add the following fields:

1) EHDEN Consortium Member (Yes/No) -> This can be useful if we have beta apps we do not want to make visible to external people. We still need to check the person is indeed a consortium member but we do not have to if they say no.

2) Data Custodian (Yes/No)

If they say yes they are given the editor role to add databases in the catalogue. 

what do you think?

**Comment by joaorafaelalmeida** [comment]
Hi Peter,
I agree with this suggestion, let me put this on the to-do list. I will look at this after the integration with WordPress.

**Comment by PRijnbeek** [comment]
@joaorafaelalmeida any updates on this? we are starting to ask data sources to create accounts

**Comment by joaorafaelalmeida** [comment]
This is already solved. The questions defined are:

- Are you an EHDEN Consortium Member? (Yes/No) 
- Are you a Data Custodian? (Yes/No)

However, if you want, we can add more questions in the Portal. Menu "Manage" -> "Join Form"
