### ISSUE TITLE
Invite user gives 404 Error

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#49]
<img width="962" alt="Screenshot 2020-10-03 at 14 06 41" src="https://user-images.githubusercontent.com/7252105/94991192-b5908700-0581-11eb-89e6-b8f8e91af56d.png">

appears after the email is sent in the backend in the Users section

**Comment by joaorafaelalmeida** [comment]
This is already fixed. The problem here was related with the redirect URL after the invite been sent. Therefore, the invites that you did previously were still sent.
