### ISSUE TITLE
Annotation Services not running?

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#50]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/7252105/94993230-c34d0900-058f-11eb-950e-9b4ca3ba9b98.png">

**Comment by joaorafaelalmeida** [comment]
This issue is already solved with the new update.

**Comment by jloliveira** [comment]
Still unstable.

**Comment by joaorafaelalmeida** [comment]
This issue was temporarily fixed by removing the annotation service and add only links to the article PubMed pages, as it was discussed with Peter in the TC on 6th of November. However, the annotation service will be fixed and activated soon.
