### ISSUE TITLE
Question on table view and filters

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#54]
We now have this:

![image](https://user-images.githubusercontent.com/7252105/95252692-9a41a800-081d-11eb-8435-debe058f1f78.png)

Is it a setting to define which fields we see here? I think it is useful to add the database Type ( can be multiple per database)?

And the country.

I assume you can the also filter by these is that correct?

Department Name we do not need in this view i think.

**Comment by aspedrosa** [comment]
These can be changed in Manage->Views. But I see that the database type is already on the list view so this was already fixed.
