### ISSUE TITLE
Text for the Achiiles Upload

### ISSUE THREAD

**Issue by joaorafaelalmeida** [EHDEN/Portal#57]
@PRijnbeek As we discussed today, we could give an explanatory text to the data custodians when they are uploading the Achilles result file. The goal of this text is to give them some confidence that they are not uploading any sensitive data and this information is beneficial to divulge their database in order to be used in studies. We can also present some levels of confidentiality based on the information uploaded, this gives the data custodian some options. However, it would be nice to encourage them to upload the full Achilles file.
You asked me to create this issue because you will write that text.

**Comment by PRijnbeek** [comment]
The data to be uploaded needs to be generated by the CatalogueExport R package (link). This is aggregated data and is not containing any patient identifiable information. We do recommend to adjust the smallCellCount setting in the package if this needs to be higher than the default of >5. It is the **responsibility of the Data Custodian** to check that no data is shared which is not allowed by the local governance rules. The package therefore contains options to only share a subset of the aggregated information if this is needed (see the package vignette for more information).
