### ISSUE TITLE
Procedure to accept new users

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#59]
There are people requesting access but we cannot see their user profile to know if we can accept them @joaorafaelalmeida.

What is the current procedure for this? 

I think it is also in another issue but it would be good if we can add some items in the application form, e.g. EHDEN Data Partner, SME.

**Comment by gklebanov** [comment]
This is why we need to use Elixir where use accounts should created and managed, including profile. Then system access can be granted there through an application specific group, and applications would received the user  id and profile info to cache for internal use.

**Comment by jloliveira** [comment]
We are currently working on the "extra fields" of the profile. Regarding the authentication through Elixir, it is available but it is not enforced (and I don't think it should be).

**Comment by aspedrosa** [comment]
The "extra fields" feature was already implemented so this can be closed.
