### ISSUE TITLE
First time upload still talks about Achilles

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#60]
![image](https://user-images.githubusercontent.com/7252105/101998828-fe2d9480-3cd6-11eb-9b61-f9c2a8c7513b.png)

(see this for the data source that were recently added)

Change Achilles to CatalogueExport

Export Achilles Results -> Execute CatalogueExport Package
The CatalogueExport package extract all data from the CDM that is needed for the dashboards.

Etc.

**Comment by PRijnbeek** [comment]
Also this message needs to change

![image](https://user-images.githubusercontent.com/7252105/102318845-43252580-3f7a-11eb-82a0-9c2e84f7ad50.png)

**Comment by joaorafaelalmeida** [comment]
This is already solved
