### ISSUE TITLE
backend query for the concept_browser_ table

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#62]
I think this one is auto generated in the database as a view not in Superset for speed

I need to change this query how can i do that? Can this query be shared so i can modify it?

**Comment by PRijnbeek** [comment]
I now created "SQL Lab" table for the new concept browser table (see the tab in the per database dashboard). 

However this is now very slow since it is not a permanent view with indexes. Can you change that, it is not clear to me how i can do that myself.

Note I had to remove this ccs to make edit buttons visible as you know:

![image](https://user-images.githubusercontent.com/7252105/102015579-c701c680-3d5c-11eb-87a6-4f0464482063.png)

**Comment by aspedrosa** [comment]
You can update it through the admin app of the Network Dashboards (http://...**/admin**). Then on the MATERIALIZED_QUERIES_MANAGER section app click on `Materialized querys`. Here you just need to find the view being used on the superset chart and edit it.

**Comment by PRijnbeek** [comment]
Thanks what is the exact link for this admin view?

**Comment by aspedrosa** [comment]
https://dashboards.ehden.eu/admin/

**Comment by PRijnbeek** [comment]
Can you send met the credentials by email: p.rijnbeek@erasmusmc.nl or make one for me?

**Comment by PRijnbeek** [comment]
Thanks this worked nicely for the new Concept Browser components now.

Is it useful to also add indexes concept_name to make the search quicker?

**Comment by PRijnbeek** [comment]
there is an issue with the views, I added a few but I i keep getting a bad gateway error and when I try again it says the view already exists but it is not in the list. For example, age_distribution_visit table.

I am not able to added new views in django no @aspedrosa can you have a look at this tomorrow? thanks

**Comment by aspedrosa** [comment]
Not sure what happened, but some containers went down what lead to the dashboard app going down as well.
They are up now, and I deleted **all** materialized views that didn't have a matching row on the MATERIALIZED_QUERIES_MANAGER section of the Network Dashboards site. I think the only you need to recreate is the `visit_type_age_distribution` one.
