### ISSUE TITLE
MetaData table filter

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#63]
![image](https://user-images.githubusercontent.com/7252105/102015481-2b705600-3d5c-11eb-9047-c201cb44d110.png)

This is not working correctly is should filter on the source_name/id but that field is not present it he underlying table.

Is this metadata table also a view you make in Postgres maybe i could not find what query is applied

**Comment by aspedrosa** [comment]
I didn't understand the problem. The filter is filtering by the data source (on the filter each option shows the data source name).
Notice that with the current height of the MetaData table you only can see one data source.
Also, I think the Demo data source currently has the name `Synpuf`.

Related to the view, it's the same process I mentioned [here](https://github.com/EHDEN/Portal/issues/62#issuecomment-744042954).

**Comment by PRijnbeek** [comment]
Ah i see the height was the problem this is fixed now
