### ISSUE TITLE
Change data stamps to text 

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#64]
I experience issues with the Execution Data, Source Update Data, Cdm Release Data not being ISO when we upload.

Can this be changed to a string so each DBMS will be able to populate this or should we fix something on the R side? It may be different for different DBMS etc.

**Comment by PRijnbeek** [comment]
Same for this one: 
![image](https://user-images.githubusercontent.com/7252105/102319096-aadb7080-3f7a-11eb-83ed-e78235876e7e.png)

The string it the file is: v5.0 25-MAY-20  What is wrong with that?

**Comment by aspedrosa** [comment]
Do you also want this behavior for the r package version?

**Comment by joaorafaelalmeida** [comment]
@aspedrosa yes

**Comment by joaorafaelalmeida** [comment]
This is already solved
