### ISSUE TITLE
Add to EHDEN domain

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#7]
Team how can we add the portal under portal.ehden.eu ?

Since it now runs under /ehden on the current server I am not sure how to add this in our ehden.eu DNS?

Any suggestions?

**Comment by joaorafaelalmeida** [comment]
Hi Peter, 
How are you?
It will be great to have the portal under this URL, but I will need some help from you. I need you to add the DNS type A for the portal.ehden.eu to  IP 193.137.169.70. Could you do this for me?

**Comment by PRijnbeek** [comment]
Done but it will now go to the bioinformatics homepage since the portal is under a folder.

You cannot set a DNS to a subfolder i think?

**Comment by PRijnbeek** [comment]
Also you need to add a certificate on that server of ehden.eu or EFPIA will not be able to connect to it.

We could also place it on a AWS instance instead of course that is very easy to do as well. Add a certificate there is straigtforward

**Comment by joaorafaelalmeida** [comment]
Ok, I contacted the IT team, and we need to discuss the certificate's issue. So, I will send you an email when the IT team provide to me the CSR certificate, and we continue this discussion by email.
