### ISSUE TITLE
New entry button only visible after clicking Catalogue

### ISSUE THREAD

**Issue by MaximMoinat** [EHDEN/Portal#71]
When someone first enters the portal and hovers over the catalogue, he/she only sees this (and maybe a 'personal' option):
![](https://github.com/EHDEN/Portal/raw/master/wiki/images/catalogue1.png)

Only after clicking on catalogue, the 'New Entry' option appears:
![](https://github.com/EHDEN/Portal/raw/master/wiki/images/catalogue2.png)

This can be confusing and make people think they don't have the right privileges to add an entry. Would it be possible to keep all the options even when not 'in' the catalogue?

**Comment by aspedrosa** [comment]
This is no longer an issue.
