### ISSUE TITLE
Freetext Search

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/Portal#81]
I tried to use the fleetext search on the top to find the IPCI database and it did not find it why?

Also searching for another text in any of the fields did not work for me.

**Comment by joaorafaelalmeida** [comment]
Hello Peter,
Did you use the free text search on the top, or on the filters by "Database name"?
I think you tried to search by database name, but IPCI is the database acronym.

Example by database name:
![dbname](https://user-images.githubusercontent.com/17878072/141387792-0182fd8b-f2fd-4e77-be86-2562cb8dd6bf.png)

Example by database acronym:
![dbacron](https://user-images.githubusercontent.com/17878072/141387795-6439e9cb-ec21-428f-8e64-11c84c4ca4d2.png)

Example using free-text search on top
![freetext](https://user-images.githubusercontent.com/17878072/141387798-6b90b6b9-0396-4da9-af44-001772cfa74c.png)

**Comment by PRijnbeek** [comment]
I used the free text: 

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/7252105/141499106-e8b69023-40a9-4f72-ad72-0b6aa097c64f.png">

**Comment by alina-trifan** [comment]
Hi @PRijnbeek, could you please provide more context on how did you get this result? We have been trying to replicate it in different browsers, but the search for ipci returns the results @joaorafaelalmeida already shared. 
Thanks!
