### ISSUE TITLE
Database logo

### ISSUE THREAD

**Issue by tajanenp** [EHDEN/Portal#82]
Dears,
I can not find a way to change our database logo :( I uploaded a temporary logo when creating the database entry and now we would like to change it into a official one, but don't find a place to do that. Many Thanks for your help already in advance.
Pia Tajanen
HDSF Finland

**Comment by aspedrosa** [comment]
Hi,
Since someone else had the same problem, the following document was created at the time, describing the procedure to solve the problem:
[Guidelines to insert logo.pdf](https://github.com/EHDEN/Portal/files/7912277/Guidelines.to.insert.logo.pdf)

**Comment by tajanenp** [comment]
THANKS SO MUCH 4 YOUR IMMEDIATE REPLY!!! You may close the issue!
