### ISSUE TITLE
Dashboard Data upload

### ISSUE THREAD

**Issue by tajanenp** [EHDEN/Portal#83]
Dears,

we have problems uploading the dasboard :( the upload seems to go through flawlessly but the results do not populate on the dashboard!! We have tried several times with a couple of versions of the csv. First try did not populate, the 2nd try did populate and was visible for about 24hrs and then it disappeared and never came back?! Today we tried again several times with no luck!
Would be great if you could help out as we need this for our Final Report which is due this week!
Many Thanks already in advance!
Pia
![image](https://user-images.githubusercontent.com/94465922/150743631-a3732406-b948-4cbe-98c1-e0be48dcd5ef.png)

**Comment by aspedrosa** [comment]
Hi,

You did everything correctly and the data is indeed uploaded. Some problem occurred and the wrong data was being fetched.
We have to look further into it but you should be able to see your data now.

**Comment by tajanenp** [comment]
We have tried to publish our dashboard by removing the tick from the Draft status tick box, but are unsure whether it worked as the Save button does not seem to have any effect and the box stays ticked. Are you able to see from somewhere whether the Community Manager has received our request to publish the dashboard?
Many Thanks again!
Pia

**Comment by aspedrosa** [comment]
There is no need to save. You just have to uncheck the tick box and a notification will be sent to the community manager.
But indeed the checkbox appears checked if you enter again on edit mode, even after unchecking.
But it seems that the community manager already accepted your request, as it is not a draft anymore.

I will close the issue, as the original problem was solved :)
